### ISSUE TITLE
Update to alpha.7

### ISSUE THREAD

**Issue by ftupas** [shramee/starklings-cairo1#100]
https://github.com/starkware-libs/cairo/releases/tag/v1.0.0-alpha.7

**Comment by ftupas** [comment]
I would like to try to do this once the hotfix `u256` div is released (ETA next week as per Shahar)

**Comment by shramee** [comment]
Hi @ftupas,
We had some stuff waiting on this. So this was prioritised higher.
Thanks for taking time to contribute!
