### ISSUE TITLE
Exercises: Math operators

### ISSUE THREAD

**Issue by shramee** [shramee/starklings-cairo1#11]

**Comment by trangnv** [comment]
Can I take this? @shramee

**Comment by trangnv** [comment]
Facing this compiling issue when I have a comment `// Return the solution of (x² + x - 2) / (x - 2)`, because of this char `²` 

```
⚠️  Compiling of exercises/operation/operation1.cairo failed! Please try again. Here's the output:
thread 'main' panicked at 'byte index 160 is not a char boundary; it is inside '²' (bytes 159..161) of `// Felts supports basic math operations.
// Only accepted operators (const excluded) are: +, -, * and /
```
Any idea @shramee @msaug ?

**Comment by shramee** [comment]
Haven't seen that before. But yeah, makes sense. Probably can't have characters outside a specific boundary. Maybe raise an issue on `starkware-libs/cairo`?

**Comment by trangnv** [comment]
it's fixed with latest `starkware-libs/cairo`, looks like you fixed here as well

**Comment by shramee** [comment]
@trangnv You can mention the issues on PR like so,
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
