### ISSUE TITLE
Contract interactions

### ISSUE THREAD

**Issue by enitrat** [shramee/starklings-cairo1#110]
These exercises will teach how to perform interactions with other contracts and libraries on Starknet.

They will cover
- Contract Dispatcher and Library Dispatchers
- call_contract syscall

**Comment by shramee** [comment]
@enitrat Seems like this might be included in exercise `starknet5`?

**Comment by enitrat** [comment]
yes indeed

**Comment by shramee** [comment]
Sweet, closing this one then. Let me know if we needed something else for this too.
