### ISSUE TITLE
Update contract syntax to Cairo v2.1.0

### ISSUE THREAD

**Issue by enitrat** [shramee/starklings-cairo1#136]

**Comment by shramee** [comment]
@codeWhizperer Sorry, this is on hold.

**Comment by enitrat** [comment]
2.1.0 is here so let's go straight to 2.1.0. It's the same Syntax anyway :)

**Comment by shramee** [comment]
Hi @codeWhizperer,
Any updates on this?

**Comment by codeWhizperer** [comment]
Yes, I am rounding up on the test and also want to make slight changes to
the readme

**Comment by shramee** [comment]
Aye, sure can @enitrat
