### ISSUE TITLE
Every exercise folder should be prefixed with a number corresponding to its order of appearance to facilitate easier tracking

### ISSUE THREAD

**Issue by uri-99** [shramee/starklings-cairo1#142]

**Comment by shramee** [comment]
This sounds like a good idea, but we might want to have exercises from different directories. For example,

* `03_section_x/ex1`
* `04_section_y/ex1`
* `04_section_y/ex2`
* `03_section_x/ex2`
* `05_section_z/ex1`

Number might make less sense in that case...
