### ISSUE TITLE
First time run - first exercise is already solved.

### ISSUE THREAD

**Issue by gpiriou** [shramee/starklings-cairo1#15]
I typed `hint` to see if I was missing something and it didn't return anything.

<img width="611" alt="Screen Shot 2023-01-31 at 22 37 10" src="https://user-images.githubusercontent.com/60015663/215889520-3df0c44a-8997-497a-88e2-f878af7717ae.png">

**Comment by shramee** [comment]
Hi @gpiriou,
Thanks for taking time to play with Starklings!
That is intentional, you will see some details when you go to the file.
Will add a comment making it clear.

**Comment by gpiriou** [comment]
Hey @shramee ! Thanks for replying so quickly ! Indeed. Will remove comment shortly.
