### ISSUE TITLE
About Struct3 exercise Hint

### ISSUE THREAD

**Issue by ASaidOguz** [shramee/starklings-cairo1#155]
In struct exercise there's wrong link leads to empty page  https://cairo-book.github.io/ch04-03-method-syntax.html
the intended page is this -> https://book.cairo-lang.org/ch05-03-method-syntax.html

However here in the page above snapshot method is introduced so the correct page for the struct3 exercise is down below
https://book.cairo-lang.org/ch05-02-an-example-program-using-structs.html

**Comment by shramee** [comment]
This is fixed.
