### ISSUE TITLE
Starknet `storage` resolution error

### ISSUE THREAD

**Issue by glihm** [shramee/starklings-cairo1#156]
After a message on discord, I've tried to run the exercise on starknet with this command:
```bash
cargo run -r --bin starklings watch starknet1
```

This error arises (compiled from main):
![image](https://github.com/shramee/starklings-cairo1/assets/7962849/0580c749-a7d1-4a38-977a-b47850873df5)

And it looks like the import from the `corelib` is not working as expected.

Will check it in detail if I can later today, @shramee perhaps you're already aware, sorry for duplicating if yes.

**Comment by yozhiik** [comment]
this made me sad for at least 3 hours, thank you for the temporary workaround! let me know if you need any more info

**Comment by glihm** [comment]
> this made me sad for at least 3 hours, thank you for the temporary workaround! let me know if you need any more info

Thanks to you man we fixed an important thing here as @enitrat said! Hopefully you'll keep enjoying Cairo! ❤️
