### ISSUE TITLE
Unnecessary `clone()` usage in move_semantics1.cairo file 

### ISSUE THREAD

**Issue by TAdev0** [shramee/starklings-cairo1#179]
Current move_semantics1 exercice implements `main` as follows : 

```
fn main() {
    let arr0 = ArrayTrait::new();

    let arr1 = fill_arr(arr0);

    // This is just a print statement for arrays.
    arr1.clone().print();

    //TODO fix the error here without modifying this line.
    arr1.append(88);

    arr1.clone().print();
}
```

Nevertheless, using `clone()` in the last line is not necessary, as ownership of `arr1` can be given to `print` method without issue because it is never used after that. It would avoid unnecessary clone call to replace `main` with :  

```
fn main() {
    let arr0 = ArrayTrait::new();

    let arr1 = fill_arr(arr0);

    // This is just a print statement for arrays.
    arr1.clone().print();

    //TODO fix the error here without modifying this line.
    arr1.append(88);

    arr1.print();
}
```

**Comment by TAdev0** [comment]
@shramee do you want me to push a PR to remove the unnecessary clone() call, or not necessary?

**Comment by shramee** [comment]
@TAdev0 Yes please ser :)
