### ISSUE TITLE
cargo build fails

### ISSUE THREAD

**Issue by nicolasbelfis** [shramee/starklings-cairo1#180]
when executing `cargo run -r --bin starklings`
`error[E0107]: struct takes 3 generic arguments but 2 generic arguments were supplied`
using rustc 1.74.1 (a28077b28 2023-12-04)
cargo 1.74.1 (ecb9851af 2023-10-18)
```
12 | pub type Map<K, V> = indexmap::IndexMap<K, V>;
   |                                ^^^^^^^^ -  - supplied 2 generic arguments
   |                                |
   |                                expected 3 generic arguments
```

**Comment by shramee** [comment]
Hi @nicolasbelfis, not really seeing this happen.
Could you try updating your cargo and rust?
