### ISSUE TITLE
add println! exercise

### ISSUE THREAD

**Issue by shramee** [shramee/starklings-cairo1#190]

**Comment by CountryCousin** [comment]
Has it been assigned??

**Comment by shramee** [comment]
Nope, ready to grab.

**Comment by manoahLinks** [comment]
Hi i am interested in this, but i need clarity if you want an upgrade of the existing print exercise or do you want a complete new exercise on println!

**Comment by shramee** [comment]
Sorry, this is already assigned.

**Comment by shramee** [comment]
There's another one left about warning in the latest Cairo version.

**Comment by manoahLinks** [comment]
i would love to hop on it, if there are guides to help out
