### ISSUE TITLE
add starknet components exercise

### ISSUE THREAD

**Issue by shramee** [shramee/starklings-cairo1#191]

**Comment by raghav-rama** [comment]
Yo, can you tell a bit more about this?

**Comment by shramee** [comment]
Hi,
This needs to be an exercise introducing components for building components.
OpenZeppelin have used these remarkably in the last version and can be used as a source of inspiration for the exercises.

**Comment by Alberto0738gh** [comment]
New

**Comment by Alberto0738gh** [comment]
New

**Comment by CountryCousin** [comment]
has it been assigned??

**Comment by CountryCousin** [comment]
oh sorry, I just noticed its been assigned.

**Comment by fishonamos** [comment]
@raghav-rama. What is the status?

**Comment by raghav-rama** [comment]
> @raghav-rama. What is the status?

WIP

**Comment by shramee** [comment]
Closed in #209
