### ISSUE TITLE
bug: LSP crash with starklings, prelude is not a core submodule.

### ISSUE THREAD

**Issue by N0lanV** [shramee/starklings-cairo1#193]
# Bug Report

**Cairo version: 2.5.3**

**Current behavior:**
LSP worker panic with Starklings-cairo1 exercices.
```
thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-semantic-2.5.3/src/corelib.rs:57:28:
`prelude` is not a core submodule.
```

**Expected behavior:**
Working like when I create a new project

**Steps to reproduce:**
Install vscode, scarb stable, add cairo 1.0 extension, clone starklings-cairo1 and open the project.

**Other information:**
![image](https://github.com/starkware-libs/cairo/assets/109871781/d01f794a-73ec-4aa3-8c5a-37758e4915f5)

**Comment by shramee** [comment]
Hi,
This seems to originate from your Cairo install.
Or you might have another dependency unintentionally named `core` (been there, done that).

**Comment by N0lanV** [comment]
Hi :hand: 
It's a fresh install of Cairo through Scarb and I've not updated any files outside of exercices folder.
![image](https://github.com/shramee/starklings-cairo1/assets/109871781/d21cb545-a700-440c-ba36-b351eca14d22)

My LSP work with a new Cairo project so the error should be in this project.

But you can close this issue if you can't replicate on your side, no problem :relaxed:

**Comment by shramee** [comment]
Aah, can you confirm if it still happens with this PR

https://github.com/shramee/starklings-cairo1/pull/188

**Comment by N0lanV** [comment]
🎉 Omedetou 🎉

Everything works now !
Thanks for your support and work 🤩
![image](https://github.com/shramee/starklings-cairo1/assets/109871781/400094a3-4c5f-453b-a3f5-3425d704b920)
