### ISSUE TITLE
Error compiling `exercises/starknet/basics/starknet3.cairo:` Missing `IProgressTracker`...

### ISSUE THREAD

**Issue by milk-maid** [shramee/starklings-cairo1#194]
I'm encountering an error while compiling the `exercises/starknet/basics/starknet3.cairo` file after I have carefully implemented all my TODOs in the Starklings codebase. Here are the details:

**Error Message:**

```bash
error: Identifier not found.
 --> /home/Documents/code/cairo_projects/starklings-cairo1/runner-crate/src/lib.cairo:21:9
    use `starknet3`::starknet3::IProgressTracker;
```

**Line Affected:**

The error occurs on line 21 of the `exercises/starknet/basics/starknet3.cairo` file:

```cairo
#[starknet::contract]
mod ProgressTracker {
@>  use starknet3::starknet3::IProgressTracker; // **Error occurs here**
    use starknet::ContractAddress;
    use starknet::get_caller_address;
}
```

**Attempted Solution**

I attempted to comment out the line `use starknet3::starknet3::IProgressTracker;,` and the code `compiled successfully`.

Could this be the permanent solution? I am eager and open to learning. Thanks

**Comment by shramee** [comment]
Hi @milk-maid,
GH is for tracking issues with code itself.
For support you can ask questions on starklings/core-stars TG group.
