### ISSUE TITLE
Error with rustc 1.77+

### ISSUE THREAD

**Issue by shramee** [shramee/starklings-cairo1#205]
Reported by @barretodavid,

```
error: failed to run custom build command for `scarb-build-metadata v2.5.3 (https://github.com/software-mansion/scarb#5189ae09)`

Caused by:
  process didn't exit successfully: `/Users/david/apps/starknet/starklings/target/release/build/scarb-build-metadata-80d95f6ce8b10254/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=../../.git/index
  cargo:rustc-env=SCARB_COMMIT_HASH=5189ae09e2be80e5ed70c0f927b0bcd297454b5d
  cargo:rustc-env=SCARB_COMMIT_SHORT_HASH=5189ae09e
  cargo:rustc-env=SCARB_COMMIT_DATE=2024-02-08
  cargo:rerun-if-changed=../../Cargo.lock

  --- stderr
  thread 'main' panicked at /Users/david/.cargo/git/checkouts/scarb-831c32bf23da0a7c/5189ae0/utils/scarb-build-metadata/build.rs:54:5:
  Expected metadata resolve root to be `scarb`.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Waiting on update on Scarb to fix for newer `rustc`.

**Comment by Zeegaths** [comment]
I'm getting the same error to run `cargo run -r --bin starklings`

**Comment by shramee** [comment]
Yeah, that's the one.
Please use rust 1.76 until this issue is fixed.

**Comment by carlosvaztec** [comment]
Same error here, thanks for creating this issue.

**Comment by shramee** [comment]
This is fixed in scarb and will be released in the next scarb release.

**Comment by sprtd** [comment]
If you have `rustup`, you can switch to `v1.7.6.0` by running the following commands:
1. `rustup toolchain install 1.76.0`
2. `run rustup default 1.76.0`  - this sets your toolchain (cargo and rustc) to v1.76.0
check the respective versions of your toolchain by running:
`rustc --version` and `cargo --version`

Make sure you see 1.76 for both rustc and cargo on your terminal. Then you can proceed to run:
`cargo run -r --bin starklings watch ⁠`

**Comment by shramee** [comment]
Thanks for the instructions @sprtd :D

**Comment by linghuccc** [comment]
> This is fixed in scarb and will be released in the next scarb release.

I am having the same issue for rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by linghuccc** [comment]
> This is fixed in scarb and will be released in the next scarb release.

I think this is not fixed in latest version:
scarb 2.6.5 (d49f54394 2024-06-11)
cairo: 2.6.4 (https://crates.io/crates/cairo-lang-compiler/2.6.4)
sierra: 1.5.0

**Comment by renzobanegass** [comment]
Hi @shramee,

As this bug has been ongoing since March and has not yet been fixed in the latest Scarb release, I propose we add it as a Known Issue to the documentation. Placing a small warning near the installation steps could be very helpful for new users. We can use the solution provided by @sprtd, as it is simple and effective.

Documenting known issues can prevent users from encountering avoidable problems, allowing them to focus on learning Cairo without unnecessary hurdles. Please let me know what you think.

Thank you!

**Comment by Olugbenga2000** [comment]
> Before the next scarb release as @shramee [mentioned](https://github.com/shramee/starklings-cairo1/issues/205#issuecomment-2090172480), if you have `rustup`, you can switch to `v1.7.6.0` by running the following commands:
> 
> 1. `rustup toolchain install 1.76.0`
> 2. `run rustup default 1.76.0`  - this sets your toolchain (cargo and rustc) to v1.76.0
>    check the respective versions of your toolchain by running:
>    `rustc --version` and `cargo --version`
> 
> Make sure you see 1.76 for both rustc and cargo on your terminal. Then you can proceed to run: `cargo run -r --bin starklings watch ⁠`
Thanks for this man

**Comment by shramee** [comment]
This is now fixed guys.
