### ISSUE TITLE
Hint for dict3 refers to a dead link

### ISSUE THREAD

**Issue by brianblank** [shramee/starklings-cairo1#211]
Hint for dict3 is as follows:

```
$ cargo run -r --bin starklings hint dict3
    Finished release [optimized] target(s) in 0.75s
     Running `target/release/starklings hint dict3`
Example of custom data structures using dicts can be found in this chapter :
https://book.cairo-lang.org/ch03-03-custom-data-structures.html
```
The link is a dead link.  I was able to recover the material from [archive.org](https://web.archive.org/web/20231202210835/https://book.cairo-lang.org/ch03-03-custom-data-structures.html) to complete the exercise.

**Comment by misicnenad** [comment]
@shramee this is an easy fix, would create a PR in minutes if you assign me.
