### ISSUE TITLE
Run `cargo run -r --bin starklings`, failed with error

### ISSUE THREAD

**Issue by qiaopengjun5162** [shramee/starklings-cairo1#215]
<img width="982" alt="image-20240721105632027" src="https://github.com/user-attachments/assets/77888813-b18a-4924-b01c-736c6aea0d2c">

rustc --version
rustc 1.81.0-nightly (506985649 2024-07-20)

cargo --version
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
cargo 1.81.0-nightly (a2b58c3da 2024-07-16)

Mac pro 16 m2

**Comment by qiaopengjun5162** [comment]
cargo update ahash@0.8
I tried using this command, but it didn't work

**Comment by Olugbenga2000** [comment]
`cargo update -p time` should fix it

**Comment by qiaopengjun5162** [comment]
`
starklings-cairo1 on  main [!] is 📦 starklings@0.1.0 via 🦀 1.82.0 via 🅒 base took 5.2s
➜
cargo run -r --bin starklings watch
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling serde v1.0.193
   Compiling thiserror v1.0.55
   Compiling rand v0.8.5
   Compiling ahash v0.7.7
   Compiling rayon-core v1.12.0
   Compiling crossbeam-deque v0.8.3
   Compiling unicode-normalization v0.1.22
   Compiling miniz_oxide v0.7.1
   Compiling crc32fast v1.3.2
   Compiling parking_lot_core v0.9.8
   Compiling same-file v1.0.6
   Compiling crossbeam-queue v0.3.8
error[E0635]: unknown feature `stdsimd`
  --> /Users/qiaopengjun/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/ahash-0.7.7/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

   Compiling walkdir v2.4.0
For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

starklings-cairo1 on  main [!] is 📦 starklings@0.1.0 via 🦀 1.82.0 via 🅒 base took 2.2s
➜
cargo update -p ahash
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
error: There are multiple `ahash` packages in your project, and the specification `ahash` is ambiguous.
Please re-run this command with one of the following specifications:
  ahash@0.7.7
  ahash@0.8.11

starklings-cairo1 on  main [!] is 📦 starklings@0.1.0 via 🦀 1.82.0 via 🅒 base
➜
cargo update -p ahash@0.8.11
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
    Updating `rsproxy-sparse` index
     Locking 0 packages to latest compatible versions
note: pass `--verbose` to see 415 unchanged dependencies behind latest

starklings-cairo1 on  main [!] is 📦 starklings@0.1.0 via 🦀 1.82.0 via 🅒 base took 5.8s
➜
cargo run -r --bin starklings watch
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/Users/qiaopengjun/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling hashbrown v0.14.3
   Compiling ahash v0.7.7
   Compiling num-bigint v0.4.4
   Compiling faster-hex v0.9.0
   Compiling aho-corasick v1.1.1
   Compiling regex-syntax v0.7.5
   Compiling parking_lot v0.12.1
   Compiling crossbeam-channel v0.5.8
   Compiling rayon-core v1.12.0
   Compiling crossbeam-queue v0.3.8
   Compiling flate2 v1.0.28
   Compiling indexmap v1.9.3
error[E0635]: unknown feature `stdsimd`
  --> /Users/qiaopengjun/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/ahash-0.7.7/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

starklings-cairo1 on  main [!] is 📦 starklings@0.1.0 via 🦀 1.82.0 via 🅒 base took 2.4s
➜`



Still no use. Tried all the methods.

**Comment by qiaopengjun5162** [comment]
<img width="943" alt="image" src="https://github.com/user-attachments/assets/da76fb8b-d6d4-406f-9046-d67c958ece05">

**Comment by Olugbenga2000** [comment]
Follow the instructions [here](https://github.com/shramee/starklings-cairo1/issues/205#issuecomment-2090229891) by @sprtd

**Comment by qiaopengjun5162** [comment]
@Olugbenga2000 Thank you very much, I have solved it according to your method
