### ISSUE TITLE
`Testing of exercises/loops/loops1.cairo failed! Please try again. Here's the output:`

### ISSUE THREAD

**Issue by CountryCousin** [shramee/starklings-cairo1#225]
```loop {
        if counter == 10{
            break ();
        }
        counter += 1;
    };
    assert(counter == 10, 'counter should be 10')
    ```
test fails even though the code is correct: This applies to the two exercises on loop

**Comment by McCoady** [comment]
Also ran into the same issue where this error would occur if I attempted to implement any additional logic inside the loop.

Eventually just switched to the web app and it worked fine. Unsure whats breaking the terminal version.
