### ISSUE TITLE
sometimes hint command fail

### ISSUE THREAD

**Issue by notV4l** [shramee/starklings-cairo1#41]
![image](https://user-images.githubusercontent.com/122404722/220937218-d3ac5ee7-db85-4cfa-b0e4-d83385926d8c.png)

**Comment by shramee** [comment]
Hi @notV4l,
Thanks a lot for reporting.
This is not a priority for us right now. We will jump in investigate this as we have better availability.
But really appreciate you taking time to report this.

Thanks!
