### ISSUE TITLE
Answer provided in first part of exercise options1.cairo

### ISSUE THREAD

**Issue by brel-baz** [shramee/starklings-cairo1#56]
The first part of exercise ask to complete the function body of maybe_icecream(time_of_day: felt) function but it's already complete with good answer !
`https://github.com/shramee/starklings-cairo1/blob/main/exercises/options/options1.cairo`

**Comment by shramee** [comment]
Aah, oops.
Thanks for reporting this too 😄 
We are working towards streamlining the contribution process, we will add the tests to catch issues like these.

**Comment by brel-baz** [comment]
You are welcolme 🫡
