### ISSUE TITLE
Links in the Hints Not working

### ISSUE THREAD

**Issue by vikkydataseo** [shramee/starklings-cairo1#77]
Most of the links  pointing to medium articles which are found if you you run `cargo run --bin starklings hint`  are not working

**Comment by shramee** [comment]
Hi @vikkydataseo,

They seem to work for me, could you point out which ones are not working for you?

**Comment by vikkydataseo** [comment]
Hey @shramee  links like this for example is not opening https://link.medium.com/c8TqX7R3qxb#6d64

**Comment by shramee** [comment]
That link opens this page for me,
https://medium.com/nethermind-eth/a-first-look-at-cairo-1-0-a-safer-stronger-simpler-provable-programming-language-892ce4c07b38#6d64

**Comment by vikkydataseo** [comment]
@shramee  check this out

![what I see](https://user-images.githubusercontent.com/65757691/226162234-83f0ab7e-258b-4263-afa4-6dc352a822b4.png)

**Comment by shramee** [comment]
Maybe try in a private window or something without any add-ons?

**Comment by vikkydataseo** [comment]
it could not open in brave, but it works in firefox...Thank you

**Comment by shramee** [comment]
All righty, we'll jump in, if we have more reports of this. Thanks.
