### ISSUE TITLE
sum_big_numbers in primitive_types4.cairo

### ISSUE THREAD

**Issue by tensojka** [shramee/starklings-cairo1#99]
```
fn sum_big_numbers(x: u8, y: u8) -> u16 {
    x + y
}
```

I changed the return value, hoping that it would automatically use the correct code path for adding u8 + u8 = u16, but the compiler doesn't seem to understand.

I get that I can first convert x and y to u16 and then sum them, but wouldn't that be inefficient (a waste of memory)? I haven't found a doc on how the uX types are actually mapped to felts and how they work.

**Comment by enitrat** [comment]
I don't think we have direct upcasting between integers yet - you might have to use a felt as an intermediary here.

**Comment by shramee** [comment]
I'mma close this for now, feel free to re-open/continue discussion.
